// Shared styles for reusable listing, cards, filters, stories, and media components.
// Grouped here to avoid scattering CSS-in-JS fragments across common components.

import { C } from "../constants/colors.js";
import { mergeStyles } from "./primitives.js";

export const CG = {
  lazyWrap: (cStyle) => ({ ...cStyle, position: "relative", overflow: "hidden", background: "#F3F4F6" }),
  lazyImage: (iStyle, loaded) => ({ ...iStyle, opacity: loaded ? 1 : 0, transition: "opacity 0.3s ease" }),
  lazyPlaceholder: { position: "absolute", inset: 0, background: "#F0F4F2", display: "flex", alignItems: "center", justifyContent: "center" },
  lazySpinner: { width: 24, height: 24, border: "2px solid #DDE8E1", borderTopColor: "#1A4A2E", borderRadius: "50%", animation: "spin 0.7s linear infinite" },
  currencyTag: (isUSD) => ({ fontSize: 10, fontWeight: 900, color: isUSD ? "#9A6B12" : "#1A4A2E", background: isUSD ? "#FFF7E6" : "#E8F4F0", borderRadius: 999, padding: "3px 9px", display: "inline-flex", alignItems: "center", justifyContent: "center", minWidth: 34, gap: 4 }),
  ownershipTag: (s) => ({ fontSize: 10, fontWeight: 700, color: s.color, background: s.bg, borderRadius: 4, padding: "2px 7px", border: "1px solid " + s.border }),
  officeBadge: { fontSize: 10, fontWeight: 700, color: C.gold, background: "#FEF3C7", borderRadius: 5, padding: "2px 8px", border: "1px solid " + C.gold2 },
  ratingEmpty: (size) => ({ fontSize: size, color: C.text3 }),
  ratingWrap: (bgColor) => ({ display:"inline-flex", alignItems:"center", gap:4, background:bgColor, borderRadius:20, padding:"2px 8px" }),
  ratingStar: (size, active, starColor) => ({ fontSize:size, color: active ? starColor : "#E5E7EB" }),
  ratingValue: (size, starColor) => ({ fontSize:size, fontWeight:700, color:starColor }),
  ratingCount: (size) => ({ fontSize:size-1, color:C.text3, fontWeight:400 }),
  weeklyCard: (DC) => ({ background: DC.white, borderRadius: 14, padding: "14px", marginBottom: 14, border: "1px solid " + DC.border, boxShadow: "0 1px 4px rgba(0,0,0,0.05)" }),
  weeklyTitle: (DC) => ({ fontSize: 15, fontWeight: 800, color: DC.text, marginBottom: 10 }),
  weeklyLoading: (DC) => ({ color: DC.text3, fontSize: 13, padding: "10px 0" }),
  weeklyGrid: { display: "grid", gap: 8 },
  weeklyItem: (DC) => ({ background: "#F8FAFC", borderRadius: 10, padding: "12px 14px", fontSize: 13, fontWeight: 700, color: DC.text }),
  bottomNavWrap: (DC) => ({ position: "fixed", bottom: 0, left: "50%", transform: "translateX(-50%)", width: "100%", maxWidth: 430, background: DC.white, borderTop: "1px solid " + DC.border, zIndex: 100 }),
  bottomNavRow: { display: "flex", padding: "8px 0 10px" },
  bottomNavButton: { flex: 1, display: "flex", flexDirection: "column", alignItems: "center", gap: 2, border: "none", background: "none", cursor: "pointer", fontFamily: "inherit" },
  bottomAddButton: (DC) => ({ width: 44, height: 44, borderRadius: "50%", background: C.primary, color: "white", fontSize: 22, display: "flex", alignItems: "center", justifyContent: "center", marginTop: -18, boxShadow: "0 2px 10px rgba(26,74,46,0.25)", border: "3px solid " + DC.white }),
  unreadDotWrap: { position: "relative", display: "inline-flex" },
  bottomIcon: (page, key, DC) => ({ fontSize: 20, color: page === key ? C.primary : DC.text2, opacity: page === key ? 1 : 0.85 }),
  unreadBadge: (DC) => ({ position: "absolute", top: -4, right: -6, background: "#EF4444", color: "white", borderRadius: "50%", minWidth: 16, height: 16, fontSize: 10, fontWeight: 800, display: "flex", alignItems: "center", justifyContent: "center", padding: "0 3px", border: "1.5px solid " + DC.white, lineHeight: 1 }),
  bottomLabel: (page, key, DC) => ({ fontSize: 10, fontWeight: 700, color: page === key ? C.primary : DC.text2, opacity: page === key ? 1 : 0.85 }),
  lightboxRoot: { position: "fixed", inset: 0, zIndex: 9999, background: "#000", display: "flex", flexDirection: "column" },
  lightboxBg: { position: "absolute", inset: 0, overflow: "hidden" },
  lightboxBgImg: { width: "100%", height: "100%", objectFit: "cover", filter: "blur(26px)", transform: "scale(1.12)", opacity: 0.42 },
  lightboxBgOverlay: { position: "absolute", inset: 0, background: "linear-gradient(to bottom, rgba(0,0,0,0.55), rgba(0,0,0,0.35), rgba(0,0,0,0.55))" },
  lightboxTop: { position: "absolute", top: 0, left: 0, right: 0, display: "flex", alignItems: "center", justifyContent: "space-between", padding: "12px 16px", background: "linear-gradient(to bottom,rgba(0,0,0,0.6),transparent)", zIndex: 2 },
  lightboxClose: { width: 36, height: 36, borderRadius: "50%", background: "rgba(255,255,255,0.15)", border: "none", color: "white", fontSize: 20, cursor: "pointer", display: "flex", alignItems: "center", justifyContent: "center" },
  lightboxCount: { color: "white", fontSize: 14, fontWeight: 800, background: "rgba(0,0,0,0.4)", borderRadius: 20, padding: "4px 12px" },
  square36: { width: 36 },
  lightboxBody: { position: "relative", zIndex: 1, flex: 1, width: "100%", display: "flex", alignItems: "center", justifyContent: "center", padding: "64px 12px 84px", boxSizing: "border-box" },
  lightboxImage: { width: "100%", height: "100%", objectFit: "contain", display: "block", userSelect: "none", transformOrigin: "center center", transition: "transform 0.1s ease", touchAction: "none" },
  lightboxBottom: { position: "absolute", bottom: 0, left: 0, right: 0, background: "linear-gradient(to top,rgba(0,0,0,0.6),transparent)", padding: "20px 16px 16px", display: "flex", flexDirection: "column", alignItems: "center", gap: 8, zIndex: 2 },
  centerDots6: { display: "flex", gap: 6, justifyContent: "center" },
  lightboxDot: (active) => ({ width: active ? 22 : 7, height: 7, borderRadius: 4, background: active ? "white" : "rgba(255,255,255,0.4)", transition: "width 0.2s", cursor: "pointer" }),
  navButtons: { display: "flex", gap: 16 },
  navCircleButton: { width: 44, height: 44, borderRadius: "50%", background: "rgba(255,255,255,0.15)", border: "1px solid rgba(255,255,255,0.2)", color: "white", fontSize: 18, cursor: "pointer" },
  galleryBottom: { position: "absolute", bottom: 0, left: 0, right: 0, background: "linear-gradient(to top,rgba(0,0,0,0.5),transparent)", padding: "16px 12px 10px", display: "flex", flexDirection: "column", alignItems: "center", gap: 5, pointerEvents: "none", zIndex: 5 },
  centerDots5: { display: "flex", gap: 5, justifyContent: "center" },
  galleryDot: (active, isVideo) => ({ width: active ? 20 : 7, height: 7, borderRadius: isVideo ? 2 : 4, background: active ? "white" : "rgba(255,255,255,0.5)", transition: "width 0.2s" }),
  galleryCount: { fontSize: 11, color: "rgba(255,255,255,0.9)", fontWeight: 800, background: "rgba(0,0,0,0.35)", borderRadius: 20, padding: "2px 10px", letterSpacing: 1 },
};

export const CC = {
  listingCard: (DC, isWant) => ({
    background: DC.white,
    borderRadius: 14,
    overflow: "hidden",
    border: `1px solid ${isWant ? "#FEF3C7" : DC.border}`,
    marginBottom: 12,
    cursor: "pointer",
    boxShadow: isWant ? "0 1px 4px rgba(234,88,12,0.08)" : "0 4px 14px rgba(0,0,0,0.18)",
  }),
  listingTopBar: (typeColor) => ({ height: 3, background: typeColor, flexShrink: 0 }),
  listingBody: { flex: 1, padding: "8px 10px", minWidth: 0, display: "flex", flexDirection: "column", justifyContent: "space-between", overflow: "hidden" },
  listingTitle: (DC) => ({ fontSize: 13, fontWeight: 800, color: DC.text, lineHeight: 1.3, whiteSpace: "nowrap", overflow: "hidden", textOverflow: "ellipsis" }),
  listingPrice: { fontSize: 13, fontWeight: 900, color: C.gold, whiteSpace: "nowrap", overflow: "hidden", textOverflow: "ellipsis" },
  listingCurrency: { fontSize: 10, color: C.gold, opacity: 0.8, flexShrink: 0 },
  listingRentSuffix: { fontSize: 9, color: C.text3, flexShrink: 0 },
  statPill: (DC, isWant) => ({ background: DC.bg2, borderRadius: 999, padding: "1px 7px", fontSize: 9, color: isWant ? "#C8952A" : DC.text2, fontWeight: 700, flexShrink: 0 }),
  ownershipPill: { background: "#E8F6EC", borderRadius: 999, padding: "1px 6px", fontSize: 9, color: "#1E7D3C", fontWeight: 700, flexShrink: 0 },
  listingMetaRow: { display: "flex", alignItems: "center", justifyContent: "space-between", overflow: "hidden" },
  listingLocation: (DC) => ({ fontSize: 10, color: DC.text3, whiteSpace: "nowrap", overflow: "hidden", textOverflow: "ellipsis", flex: 1 }),
  listingTimeCol: { display: "flex", flexDirection: "column", alignItems: "flex-start", flexShrink: 0, marginRight: 4, gap: 1 },
  listingTime: (DC) => ({ fontSize: 10, color: DC.text3 }),
  listingTimeAgo: (DC) => ({ fontSize: 9, color: DC.text3, opacity: 0.75 }),
  sellerAvatar: (accountType) => ({ width: 16, height: 16, borderRadius: "50%", background: accountType === "office" ? C.gold : C.primary, color: "white", fontSize: 7, fontWeight: 700, display: "flex", alignItems: "center", justifyContent: "center", flexShrink: 0 }),
  sellerName: { fontSize: 10, color: C.text2, fontWeight: 600, whiteSpace: "nowrap", overflow: "hidden", textOverflow: "ellipsis" },
  verifiedTick: { fontSize: 9, color: C.primary2, fontWeight: 700 },
  expiryBox: (bg, urgent, expired) => ({ background: bg, borderRadius: 6, padding: "4px 8px", border: urgent ? `1px solid ${expired ? "#FECACA" : "#FDE68A"}` : "none" }),
  expiryHead: { display: "flex", justifyContent: "space-between", marginBottom: 2 },
  expiryLabel: (color) => ({ fontSize: 9, fontWeight: 800, color }),
  expiryValue: (color) => ({ fontSize: 9, color }),
  expiryTrack: { height: 3, background: "rgba(0,0,0,0.08)", borderRadius: 3, overflow: "hidden" },
  expiryFill: (pct, color) => ({ height: "100%", width: `${pct}%`, background: color, borderRadius: 3 }),
  actionRow: (DC) => ({ display: "flex", gap: 0, borderTop: `1px solid ${DC.border}` }),
  ownerActionButton: (extra) => mergeStyles({ flex: 1, padding: "8px 4px", border: "none", fontSize: 11, fontWeight: 700, cursor: "pointer", fontFamily: "inherit" }, extra),
  adminActionButton: (DC, extra) => mergeStyles({ flex:1, padding:"9px", border:"none", borderLeft:`1px solid ${DC.border}`, fontSize:11, fontWeight:700, cursor:"pointer", fontFamily:"inherit" }, extra),
  pendingActionButton: (extra) => mergeStyles({ flex: 1, padding: "12px", border: "none", fontSize: 13, fontWeight: 800, cursor: "pointer", fontFamily: "inherit" }, extra),
  filterRoot: (DC) => ({ position:"sticky", top:0, zIndex:50, background:DC.white, borderBottom:`1px solid ${DC.border}` }),
  filterScroll: { display:"flex", gap:8, padding:"12px 14px 8px", overflowX:"auto", scrollbarWidth:"none", alignItems:"center" },
  filterPill: (DC, active, open, pillColor, pillBg) => ({ display:"flex", alignItems:"center", gap:5, padding:"8px 14px", borderRadius:22, border:`1.5px solid ${active || open ? pillColor : DC.border}`, background: active || open ? pillBg : DC.white, color: active ? pillColor : DC.text2, fontSize:12, fontWeight:active ? 800 : 600, cursor:"pointer", fontFamily:"inherit", whiteSpace:"nowrap", flexShrink:0, transition:"all 0.15s", boxShadow: active || open ? "none" : "0 1px 3px rgba(0,0,0,0.08)" }),
  filterClear: (pillColor) => ({ fontSize:11, color:pillColor, marginRight:2 }),
  filterChevron: (DC) => ({ fontSize:9, color:DC.text3 }),
  savedButton: (active) => ({ display:"flex", alignItems:"center", gap:5, padding:"7px 12px", borderRadius:20, border:`1.5px solid ${active ? "#C8952A" : "#E8B84B"}`, background: active ? "#C8952A" : "#FFFBEB", color: active ? "white" : "#92400E", fontSize:12, fontWeight:700, cursor:"pointer", fontFamily:"inherit", whiteSpace:"nowrap", flexShrink:0 }),
  savedCount: (active) => ({ fontSize:10, background:active ? "rgba(255,255,255,0.3)" : "#C8952A", color:"white", borderRadius:"50%", width:16, height:16, display:"flex", alignItems:"center", justifyContent:"center", fontWeight:900 }),
  savedChevron: (active) => ({ fontSize:9, color:active ? "rgba(255,255,255,0.7)" : "#C8952A" }),
  saveButton: { padding:"7px 11px", borderRadius:20, border:`1.5px solid ${C.primary}`, background:"#E8F4F0", color:C.primary, fontSize:11, fontWeight:700, cursor:"pointer", fontFamily:"inherit", whiteSpace:"nowrap", flexShrink:0 },
  clearButton: { padding:"7px 11px", borderRadius:20, border:"1.5px solid #FCA5A5", background:"#FEF2F2", color:C.danger || "#EF4444", fontSize:11, fontWeight:700, cursor:"pointer", fontFamily:"inherit", whiteSpace:"nowrap", flexShrink:0 },
  filterSheet: (DC) => ({ borderTop:`1px solid ${DC.border}`, padding:"12px 14px 16px", background:DC.white }),
  filterWrap7: { display:"flex", flexWrap:"wrap", gap:7 },
  filterWrap6: { display:"flex", flexWrap:"wrap", gap:6 },
  filterColumn6: { display:"flex", flexDirection:"column", gap:6 },
  pickerOption: (DC, active, activeColor, activeBg, extra = null) => mergeStyles({ padding:"8px 14px", borderRadius:20, border:`1.5px solid ${active ? activeColor : DC.border}`, background:active ? activeBg : DC.white, color:active ? activeColor : DC.text2, fontSize:12, fontWeight:active ? 800 : 500, cursor:"pointer", fontFamily:"inherit" }, extra),
  valueChip: (DC, active) => ({ padding:"8px 14px", borderRadius:20, cursor:"pointer", fontFamily:"inherit", fontSize:13, fontWeight:600, border:`1.5px solid ${active ? C.primary : DC.border}`, background: active ? C.primary + "15" : "transparent", color: active ? C.primary : DC.text }),
  listButton: (DC, active) => ({ padding:"10px 14px", borderRadius:10, border:`1.5px solid ${active ? C.primary : DC.border}`, background:active ? "#E8F4F0" : DC.white, color:active ? C.primary : DC.text2, fontSize:13, fontWeight:active ? 800 : 500, cursor:"pointer", fontFamily:"inherit", textAlign:"right", display:"flex", alignItems:"center", gap:8 }),
  savedSearchRow: (DC, active) => ({ display:"flex", alignItems:"center", gap:10, padding:"11px 14px", borderRadius:12, background:active ? "#FEF3C7" : DC.white, border:`1.5px solid ${active ? "#E8B84B" : DC.border}`, transition:"all 0.18s" }),
  savedSearchText: { flex:1, minWidth:0, cursor:"pointer" },
  savedSearchTitle: (DC) => ({ fontSize:13, fontWeight:800, color:DC.text, marginBottom:3, overflow:"hidden", textOverflow:"ellipsis", whiteSpace:"nowrap" }),
  toggleSwitch: (DC, active) => ({ width:36, height:20, borderRadius:10, background:active ? C.primary : DC.border, position:"relative", cursor:"pointer", flexShrink:0, transition:"background 0.2s" }),
  toggleKnob: (active) => ({ position:"absolute", top:2, right:active ? 2 : 18, width:16, height:16, borderRadius:"50%", background:"white", boxShadow:"0 1px 3px rgba(0,0,0,0.2)", transition:"right 0.2s" }),
  deleteSavedSearch: { width:28, height:28, borderRadius:"50%", border:"none", background:"#FEF2F2", color:"#EF4444", fontSize:14, cursor:"pointer", display:"flex", alignItems:"center", justifyContent:"center", flexShrink:0 },
  moreRangeRow: { display:"flex", gap:8, alignItems:"center", marginBottom:10 },
  moreInput: (DC) => ({ flex:1, padding:"8px", border:`1.5px solid ${DC.border}`, borderRadius:10, fontFamily:"inherit", fontSize:13, background:DC.white, outline:"none" }),
  filterFooter: (DC) => ({ display:"flex", alignItems:"center", justifyContent:"space-between", padding:"5px 14px 8px", borderTop:`1px solid ${DC.border}` }),
  resultCount: (DC) => ({ fontSize:11, color:DC.text3, fontWeight:600 }),
};
