// أنماط AppShell — أُخرجت من المكوّن الرئيسي للحفاظ على وضوح الكود
import { C } from "../../shared/constants/colors.js";

export function getAppShellStyles(DC, lang) {
  return {
    s1: {
      fontSize: 36,
      marginBottom: 10,
    },
    s2: {
      marginTop: 12,
    },
    s3: {
      marginTop: 12,
    },
    s4: {
      marginTop: 12,
    },
    s5: {
      position: "relative",
      background: DC.white,
      borderRadius: "22px 22px 0 0",
      padding: "24px 20px 44px",
      maxWidth: 430,
      width: "100%",
      margin: "0 auto",
    },
    root: {
      background: DC.bg,
      minHeight: "100vh",
    },
    shell: {
      maxWidth: 430,
      margin: "0 auto",
      background: DC.bg,
      minHeight: "100vh",
      fontFamily: lang === "ar" ? "Tajawal, sans-serif" : "'Inter', sans-serif",
      direction: lang === "ar" ? "rtl" : "ltr",
      position: "relative",
      transition: "background 0.3s",
    },
    bottomSheetWrap: {
      position: "fixed",
      inset: 0,
      zIndex: 999,
      display: "flex",
      flexDirection: "column",
      justifyContent: "flex-end",
    },
    overlayDark: {
      position: "absolute",
      inset: 0,
      background: "rgba(0,0,0,0.5)",
    },
    overlaySoft: {
      position: "absolute",
      inset: 0,
      background: "rgba(0,0,0,0.45)",
    },
    sheet: {
      position: "relative",
      background: DC.white,
      borderRadius: "22px 22px 0 0",
      padding: "24px 20px 44px",
      maxWidth: 430,
      width: "100%",
      margin: "0 auto",
    },
    handle: {
      width: 40,
      height: 4,
      background: DC.border,
      borderRadius: 2,
      margin: "0 auto 20px",
    },
    centerBlock: {
      textAlign: "center",
      marginBottom: 20,
    },
    centerBlockSmall: {
      textAlign: "center",
      marginBottom: 14,
    },
    title17: {
      fontSize: 17,
      fontWeight: 900,
      color: DC.text,
      marginBottom: 6,
    },
    text13: {
      fontSize: 13,
      color: DC.text3,
    },
    termsBox: {
      display: "flex",
      alignItems: "flex-start",
      gap: 10,
      marginBottom: 14,
      padding: "11px 14px",
      background: "#FFFBEB",
      borderRadius: 12,
      border: "1px solid #FCD34D",
    },
    termsCheck: (checked) => ({
      width: 20,
      height: 20,
      borderRadius: 5,
      border: `2px solid ${checked ? C.primary : "#D1D5DB"}`,
      background: checked ? C.primary : "white",
      flexShrink: 0,
      marginTop: 1,
      cursor: "pointer",
      display: "flex",
      alignItems: "center",
      justifyContent: "center",
    }),
    termsCheckMark: {
      color: "white",
      fontSize: 11,
      fontWeight: 900,
    },
    termsText: {
      fontSize: 12,
      color: "#374151",
      lineHeight: 1.7,
    },
    termsLink: {
      color: C.primary,
      fontWeight: 800,
      cursor: "pointer",
      textDecoration: "underline",
    },
    accountButtons: {
      display: "flex",
      gap: 10,
      marginBottom: 16,
    },
    accountButton: (enabled) => ({
      flex: 1,
      padding: "14px 10px",
      borderRadius: 14,
      border: `2px solid ${enabled ? C.primary : "#D1D5DB"}`,
      background: enabled ? "#E8F4F0" : "#F9FAFB",
      cursor: enabled ? "pointer" : "not-allowed",
      fontFamily: "inherit",
      textAlign: "center",
      opacity: enabled ? 1 : 0.5,
    }),
    accountIcon: {
      fontSize: 28,
      marginBottom: 6,
    },
    accountLabel: (enabled) => ({
      fontSize: 14,
      fontWeight: 800,
      color: enabled ? C.primary : "#9CA3AF",
    }),
    accountDesc: {
      fontSize: 11,
      color: DC.text3,
      marginTop: 4,
      lineHeight: 1.4,
    },
    linkBtn: {
      width: "100%",
      padding: "8px",
      background: "none",
      border: "none",
      color: C.primary,
      fontSize: 12,
      cursor: "pointer",
      fontFamily: "inherit",
      textDecoration: "underline",
      marginBottom: 4,
    },
    whiteSheet: {
      position: "relative",
      background: "white",
      borderRadius: "22px 22px 0 0",
      maxHeight: "80vh",
      display: "flex",
      flexDirection: "column",
    },
    sheetHeader: {
      padding: "16px 20px 12px",
      borderBottom: "1px solid #E5E7EB",
      display: "flex",
      alignItems: "center",
      justifyContent: "space-between",
      flexShrink: 0,
    },
    sheetHeaderTitle: {
      fontSize: 15,
      fontWeight: 900,
      color: "#1A2E20",
    },
    closeBtn: {
      width: 32,
      height: 32,
      borderRadius: "50%",
      border: "none",
      background: "#F3F4F6",
      fontSize: 16,
      cursor: "pointer",
    },
    sheetBody: {
      overflowY: "auto",
      padding: "16px 20px",
      fontSize: 12,
      color: "#374151",
      lineHeight: 1.9,
      direction: "rtl",
    },
    sheetFooter: {
      padding: "14px 20px 30px",
      flexShrink: 0,
      borderTop: "1px solid #E5E7EB",
    },
    primaryAction: {
      width: "100%",
      padding: "13px",
      background: C.primary,
      color: "white",
      border: "none",
      borderRadius: 12,
      fontSize: 14,
      fontWeight: 800,
      fontFamily: "inherit",
      cursor: "pointer",
    },
    loginIconWrap: {
      width: 60,
      height: 60,
      borderRadius: "50%",
      background: "#E8F4F0",
      display: "flex",
      alignItems: "center",
      justifyContent: "center",
      fontSize: 28,
      margin: "0 auto 12px",
    },
    loginText: {
      fontSize: 13,
      color: DC.text3,
      lineHeight: 1.7,
    },
    loginPrimary: {
      width: "100%",
      padding: "14px",
      background: C.primary,
      color: "white",
      border: "none",
      borderRadius: 12,
      fontSize: 15,
      fontWeight: 800,
      fontFamily: "inherit",
      cursor: "pointer",
      marginBottom: 10,
    },
    loginSecondary: {
      width: "100%",
      padding: "12px",
      background: "transparent",
      color: DC.text3,
      border: `1.5px solid ${DC.border}`,
      borderRadius: 12,
      fontSize: 14,
      fontWeight: 600,
      fontFamily: "inherit",
      cursor: "pointer",
    },
    deniedWrap: {
      position: "fixed",
      inset: 0,
      zIndex: 9999,
      background: "rgba(0,0,0,0.5)",
      display: "flex",
      alignItems: "flex-end",
      justifyContent: "center",
    },
    deniedSheet: {
      background: "white",
      borderRadius: "20px 20px 0 0",
      padding: "24px 20px 40px",
      width: "100%",
      maxWidth: 430,
      fontFamily: "Tajawal,sans-serif",
      direction: "rtl",
    },
    deniedHandle: {
      width: 40,
      height: 4,
      borderRadius: 2,
      background: "#E5E7EB",
      margin: "0 auto 20px",
    },
    deniedEmoji: {
      fontSize: 32,
      textAlign: "center",
      marginBottom: 12,
    },
    deniedTitle: {
      fontSize: 16,
      fontWeight: 800,
      color: "#1A2E20",
      textAlign: "center",
      marginBottom: 8,
    },
    deniedText: {
      fontSize: 13,
      color: "#6B7280",
      textAlign: "center",
      lineHeight: 1.8,
      marginBottom: 20,
    },
    androidBox: {
      background: "#F0FDF4",
      borderRadius: 12,
      padding: "14px 16px",
      marginBottom: 10,
      border: "1px solid #BBF7D0",
    },
    iosBox: {
      background: "#EFF6FF",
      borderRadius: 12,
      padding: "14px 16px",
      marginBottom: 20,
      border: "1px solid #BFDBFE",
    },
    androidTitle: {
      fontSize: 12,
      fontWeight: 800,
      color: "#16A34A",
      marginBottom: 6,
    },
    iosTitle: {
      fontSize: 12,
      fontWeight: 800,
      color: "#2563EB",
      marginBottom: 6,
    },
    darkPrimaryBtn: {
      width: "100%",
      padding: "13px",
      borderRadius: 12,
      border: "none",
      background: "#1A4A2E",
      color: "white",
      fontSize: 14,
      fontWeight: 700,
      cursor: "pointer",
      fontFamily: "inherit",
    },
  };
}
